spring:
  datasource:
    url: jdbc:h2:mem:libreria
    driver-class-name: org.h2.Driver
    username: admin
    password: 12345678
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
app:
  endpoint:
    usuarios: /api/usuarios